import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import Link from "next/link";
import * as s from "../../styles/common.style";
import { useRouter } from 'next/router';

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const router = useRouter()
  return (
    <>
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
      <s.LoginMain>
        <div className="login-main">
          <div className="login-left">
            <div className="login-left-inner">
              <Link href="">
                <img src="assets/logo.svg" alt="logo"></img>
              </Link>
              <h1>Login</h1>
              <s.CommonForm>
                <div className="form-group">
                  <label>
                    Username <span>*</span>
                  </label>
                  <input
                    type="text"
                    className="form-control"
                    placeholder="Enter username here"
                  ></input>
                </div>
                <div className="form-group">
                  <label>
                    Password <span>*</span>
                  </label>
                  <input
                    type="password"
                    className="form-control"
                    placeholder="Enter password here"
                  ></input>
                </div>
                <div className="login-from-inner">
                  <p>
                    <span>* </span>Denotes compulsory fields
                  </p>
                  <button 
                    // type="submit"
                    className="btn common-button" onClick={()=>router.push("/dashboard")}>
                    Sign In
                  </button>
                </div>
              </s.CommonForm>
            </div>
          </div>
          <div className="login-right">
            <img src="assets/banner-img.svg" alt="banner-img"></img>
          </div>
        </div>
      </s.LoginMain>
    </>
  );
}
